<tile>
  <visual lang="en-US" version="3">
      <binding template="TileSquare150x150PeekImageAndText02" branding="logo">
        <image id="1" src="<?php echo $this->base; ?>win8-150-icon.png" alt="shomyo" />
        <text id="2">shomyo</text>
      </binding>

      <binding template="TileSquare71x71IconWithBadge" branding="logo">
        <image id="1" src="<?php echo $this->base; ?>win8-71-icon.png" alt="shomyo" />
      </binding>

      <binding template="TileSquare150x150IconWithBadge" branding="logo">
        <image id="1" src="<?php echo $this->base; ?>win8-150-icon.png" alt="shomyo" />
      </binding>
  </visual>
</tile>
